### PR TITLE
wrap each line in element

### PR DESCRIPTION
**Pull request by conorhastings**

### CODE REVIEW

**Comment by bmathews** [comment]
This seems like the right idea, yeah! Traverse and find a `\n`, then wrap a new vdom node around everything between it and the previous `\n`. 

I haven't looked too closely at the lowlight output to know if you'll ever need to split any existing vdom nodes up or deal with any nesting/recursion in existing nodes.

Looks like a fun problem to solve! I'm trying to meet a tight deadline at work for the next month, so no spare time for me at the moment. :'(

**Comment by conorhastings** [comment]
@bmathews no problem, also on deadlines so will be working this sparingly :/

The lowlight output isn't too bad, but yeah will need to split existing vdom nodes into multiples, some have multiple /ns. on the + side there is never more than 1 level of nesting

effectively tree is something like this
```
text
text
span
  text
  text 
span
  text
  text
text
```
but never additional spans under spans so workable!

**Comment by conorhastings** [comment]
@bmathews believe current implementation basically works. code is super messy, since i was just messing around making stuff work. I'm going to continue refining / playing around with different code examples to make sure i don't break but check it out if you get a chance.

**Comment by conorhastings** [comment]
seems to be made easier by the fact that non top level nodes don't have linebreaks

**Comment by bmathews** [comment]
Nice! That's looking great! Verifying it works for various languages/examples, then adding an API for styling the lines, and this will be 👌

**Comment by conorhastings** [comment]
@bmathews tested some more and implemented some fixes - published `5.0.0-rc.1` on the `next` tag if you/anyone wants to try it out

**Pull request merged**
