### PR TITLE
support refractor

### PR DESCRIPTION
**Pull request by conorhastings**

### CODE REVIEW

**Comment by maxmcd** [comment]
`hljs` is used in `react-native-syntax-highlighter`, and other places I imagine

Is there a desire to maintain some kind of master container class, or would that just be left up to the user to figure out?

**Comment by conorhastings** [comment]
@maxmcd not sure what you mean by master class container? 

One option would be letting native accept a version of syntax highlighter and default to hljs version

**Comment by conorhastings** [comment]
@maxmcd think it basically works now, would like to address your comments re: native tho

**Comment by conorhastings** [comment]
@maxmcd gonna merge this, then perhaps we can discuss adding an option react-native-syntax-highlighter that would allow using prism version

**Comment by maxmcd** [comment]
This is great, that all happened quite quickly.

The hljs class just provided a nice bit of convenience as it could be used to easily infer the global background and default text color style. The prism styles are messier.

I see that this has been solved here: 
```js
 const defaultPreStyle = (
      style.hljs || 
      style['pre[class*=\"language-\"]'] || 
      { backgroundColor: '#fff' }
    );
```

I has just assumed that re-organizing the prism styles would be a more appropriate solution, but this seems to work quite well. Seems that the same strategy could be used with react-native-syntax-highlighter.

**Comment by conorhastings** [comment]
@maxmcd agreed a similar strategy could be used for native, I think since bundle size is less of a concern on native there is a potential 'nother approach to take

```jsx
import SyntaxHighlighterHLJS from 'react-syntax-highligher';
import SyntaxHighlighterPrism from 'react-syntax-highligher/prism';

function NativeSyntaxHighlighter({ fontFamily, fontSize, style, children, astGenerator, ...rest}) {
  const { transformedStyle, defaultColor } = generateNewStylesheet(style);
  const SyntaxHighlighter = (
    astGenerator && 
    astGenerator = "prism" ?
    SyntaxHighlighterPrism : 
    SyntaxHighlighterHLJS. 
);
  return (
    <SyntaxHighlighter
      {...rest}
      style={transformedStyle}
      horizontal={true}
      renderer={(nativeRenderer({
        defaultColor,
        fontFamily,
        fontSize
      }))}
    >
      {children}
    </SyntaxHighlighter>
  );
}

**Pull request merged**
