### PR TITLE
Update Demo for VS Code Dark

### PR DESCRIPTION
**Pull request by karlhorky**
Just a PR to update the demo on GitHub Pages.

Hm, looks like this doesn't merge cleanly... Just the `AVAILABLE_STYLES_PRISM.MD` file though.

Ref: #184
Ref: #185

### CODE REVIEW

**Comment by karlhorky** [comment]
@conorhastings is this the correct way for the demo to be updated? Otherwise I can just close this PR...

**Comment by conorhastings** [comment]
@karlhorky sorry been busy with work, this is thte first theme to come in not from prism or hljs directly and build is builtt around that i'll resolve and update tehe branch as soon as ic an

**Comment by karlhorky** [comment]
Ok, no worries, just wanted to make sure that this wasn't completely wrong.

**Comment by karlhorky** [comment]
@conorhastings friendly ping :) any chance on getting the demo with the new themes online?

**Comment by karlhorky** [comment]
@conorhastings I guess this PR is not a priority right now, closing.

**Pull request closed without merging**
