### PR TITLE
Moved prism-themes dependency to dev-dependencies

### PR DESCRIPTION
**Pull request by GeeWizWow**

### CODE REVIEW

**Comment by conorhastings** [comment]
any idea why package-lock changed so much?

Also think i prefer your suggestion in #95 to switch to npm version, let me know what you think.

**Comment by GeeWizWow** [comment]
It looks like it only holds prod dependencies now, not 100% sure. Which would be desirable, even when using npm install --production, npm will use the lock file which could still contain dev dependencies

Re the npm package, it doesn't look like it's had an update in a year, which might not bother you?

**Comment by conorhastings** [comment]
this looks good then, thanks for loooking at (re: prism themes updating), my only concern is in the future people will just do npm install when making pr and we'll see big thrash in the lock

```
    "acorn": {
      "version": "4.0.13",
      "resolved": "https://registry.npmjs.org/acorn/-/acorn-4.0.13.tgz",
      "integrity": "sha1-EFSVrlNh1pe9GVyCUZLhrX8lN4c=",
      "dev": true
    },
```

it looks like the package-lock.json marks things as dev so shouldn't install with a prod install?

**Comment by GeeWizWow** [comment]
I just had a chat with a colleague, and it looks like our environment will ignore the package-lock.json file anyway, so for us it's not an issue and can be reverted back....

as long as prism-themes is listed as a dev-dependency we should be good.
Would be nice to get it from npm instead but that might have to be a future pr. I think the prism-theme dev's wanted to setup CD but it was never done

**Comment by conorhastings** [comment]
@GeeWizWow that sounds good, yeah if the npm package is kept relatively up to date that's ideal i'll monitor the issue you created there

**Comment by GeeWizWow** [comment]
Hey, package-lock.json is now reverted

**Pull request merged**
