### PR TITLE
Use rollup for build system

### LINKED ISSUE #167: Improve build system
**Is your feature request related to a problem? Please describe.**
You have a lot of big files, that are exported and do not add a way to easily import them. All files exists in the `/dist/` but docs say to import them directly.

**Describe the solution you'd like**
1. Publish only bundled folder as we are doing in [material-ui-pickers](https://github.com/dmtrKovalenko/material-ui-pickers/tree/develop/lib)
2. Provide `esm` build with [rollup](https://rollupjs.org/guide/en) to be sure treeshaking works if we are importing from entry point (index.js file)

I can help with a build system and open a PR. Cause we are using this project and it is really nice.

### PR DESCRIPTION
**Pull request by dmtrKovalenko**
This PR updates build system. Closes #167 

### Here what's changed
1. Use folder `build` to create isolated bundle with its own `package.json`, `LICENSE` and `README.md` to publish only it. This increases package loading speed and makes available imports like `react-syntax-highlighter/languages` - without additional `dist` folder. Please note that from now you need to publish not the whole project but only folder build (`npm publish build`)
2. Use rollup to bundle `esm` bundle, which will be resolved by the `module` `package.json` field. 
3. Use rollup to create `cjs` bundle, which will be resolved by the `main`
4. Create `umd` modue with minified analog
5. Add [size-snapshot](https://github.com/TrySound/rollup-plugin-size-snapshot) plugin to easily check bundle size changes in code review. 

### Possible adjustments
1. Do not build the whole `src` folder with babel in script `build:cjs`, only build languages and styles
2. Combine some files from root to separate folders. Such files like `webpack.config.js` can be moved to `demo` for better readability. 

P.S. This PR introduced breaking changes in imports.
```diff
- import jsx from 'react-syntax-highlighter/dist/languages/prism/jsx';
- import prism from 'react-syntax-highlighter/dist/styles/prism/prism'; 

+ import jsx from 'react-syntax-highlighter/languages/prism/jsx';
+ import prism from 'react-syntax-highlighter/styles/prism/prism';

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
And also it breaks typescript typings. They must be updated :)

**Comment by marcodejongh** [comment]
@dmtrKovalenko What happens with the code splits when using rollup? It appears that rollup builds everything into single files? Doesn't that mean it breaks all of the code splits?

**Comment by dmtrKovalenko** [comment]
Actually no. Not the splitting for the files making the codesplit works. But following esmodules convention. 
When your are bundling with rollup for ram. For webpack or any other bundle it is possible to determine which code was not imported. 
When you are bundling cjs modules (with require) and you will import code from entry point you will get all imports appeared in the code anyway. Cause require is a dynamic function

**Comment by dmtrKovalenko** [comment]
Read more here
https://rollupjs.org/guide/en

**Comment by dmtrKovalenko** [comment]
And also with rollup it’s not including languages and styles. Dynamic imports works perfectly as they are a part of esmodules. And they was never work in cjs. 
I have tested locally by linking this pr to my existing project. And this change reduced bundle size a bit.

**Comment by marcodejongh** [comment]
Thanks for clarifying, I'll try this branch out tomorrow myself because it seems like a risky change.

**Comment by marcodejongh** [comment]
Looking at this PR now

**Comment by marcodejongh** [comment]
Had a look and I don't see the code splits working at all? 
The examples were broken so fixed that in https://github.com/conorhastings/react-syntax-highlighter/commit/a9aa134f1379eeadd22b3f5f24ad21ea8f478126 you probably want to cherry pick that to your branch.

But when I'm testing it locally on the async example I just see one giant bundle containing all the splits.

**Comment by dmtrKovalenko** [comment]
Ohhhh god, I forgot about this PR :)
Ooopsy

**Pull request closed without merging**
