### PR TITLE
Improved line number rendering

### PR DESCRIPTION
**Pull request by simmerer**
I've reimplemented line numbering here in a way that's compatible with `react-syntax-highlighter-virtualized-renderer` (see  [react-syntax-highlighter-virtualized-renderer/issues/3](https://github.com/conorhastings/react-syntax-highlighter-virtualized-renderer/issues/3))

## Changes

1.  When `showLineNumbers === true` and `showInlineLineNumbers === true`, line numbers are rendered as child elements of each line in the code tree, instead of being rendered in a separate `<code>` block from the code itself. 
2. In order for these new line numbers elements to maintain a consistent width, we calculate the string length of the largest line number being shown, and set that value in `em` units as the `min-width` for all line number elements.
3. These new line number elements are styled with `user-select: none` to prevent them from being mixed into code selection, e.g. when selecting + copying code from a highlighted piece of code.
4. Inline line numbering is optional via `showInlineLineNumbers` prop, which defaults to `false`.
5. Inline line numbering is available even when `wrapLines === false`.

##  Considerations

Anyone using this who has applied custom styling via `lineNumberContainerStyle` might need to migrate some styling, as there is no longer a parent "line number container" element.

Anyone using this who has applied custom styling via `lineNumberStyle` shouldn't see any difference. All properties passed via `lineNumberStyle` will override default styling for line number elements.

> One possible exception: the new line number elements must remain `display: inline-block`. If previous `lineNumberStyle` properties had included some other value for `display`, the result might appear broken.

Anyone using this with a custom renderer (virtualized or otherwise) will want to test this carefully.

### CODE REVIEW

**Comment by simmerer** [comment]
@jonheslop I saw your comment over on https://github.com/conorhastings/react-syntax-highlighter/pull/231, and thought you might also be interested in this approach.

**Comment by conorhastings** [comment]
@simmerer two considerations, i hate  upping api surface area but maybe make it option at least for one version and also is it possible to remove parent container for both

**Comment by simmerer** [comment]
> maybe make it option at least for one version

Sure, something like `showInlineLineNumbers = {true}` to only apply the new rendering style if explicitly indicated?

> is it possible to remove parent container for both

Shouldn't be too difficult.

**Comment by conorhastings** [comment]
would happily approve if we could get those two things in

**Comment by simmerer** [comment]
Ok @conorhastings, I think we're good to go with those two requested changes.

1. `showInlineLineNumbers` prop added, defaults to `false`
2. When set to `true`, line numbers get inlined regardless of `wrapLines`

**Comment by conorhastings** [comment]
will take a look tonight

**Comment by simmerer** [comment]
Gentle bump here @conorhastings ... would love to see this in a release soon if it's up to your standards.

**Comment by conorhastings** [comment]
sorry about that, merged but tests are failing now will have to track doown wht beffore a release

**Comment by simmerer** [comment]
Sorry, my bad for using `.flat()`. I'll have a fix ready in a sec

**Comment by simmerer** [comment]
https://github.com/conorhastings/react-syntax-highlighter/pull/249

**Pull request merged**
