### PR TITLE
Export createElement from light module

### PR DESCRIPTION
**Pull request by ibrahima**
Allows using createElement easily when using the light build, without pulling in all languages.

### CODE REVIEW

**Comment by conorhastings** [comment]
do you have an idea how much bigger this makes the light build by any chance?

**Comment by ibrahima** [comment]
Oh I'm not sure, I just assumed it wouldn't make much of a difference because create-element.js is pretty small. It'd be nice to have some way to import createElement in the light build though, without having to import the main package, because importing the main package causes it to pull in all the language syntax highlighting files. Right now we can still do this by importing from `'react-syntax-highlighter/dist'`, but that feels a bit wrong.

I'll try and do a build and report back. Thanks!

**Comment by conorhastings** [comment]
what version are you on, you shouldn't have to reach into the dist, just react-syntax-highlighter/create-element

**Comment by ibrahima** [comment]
Oh huh, I was on 5.7.0. Updating to a newer version should hopefully fix that. Never mind then!

**Pull request closed without merging**
